### ISSUE TITLE
Shortcut

### ISSUE THREAD

**Issue by tlextrait-ef** [insanoid/CleanHeaders-Xcode#4]
Is the shortcut Command + Pipe? I can't access the pipe without Shift and Command+Shift+Pipe won't work

**Comment by insanoid** [comment]
Yea the short-cut is correct, you will need Shift. Ensure that the plugin is correctly installed, it should appear in the menu too (see screenshot).
<img width="330" alt="screen shot 2015-12-10 at 15 32 40" src="https://cloud.githubusercontent.com/assets/193717/11712476/694a66b6-9f53-11e5-8c77-42ec26df5a28.png">
