### ISSUE TITLE
Not work in Xcode 7.2

### ISSUE THREAD

**Issue by Whirlwind** [insanoid/CleanHeaders-Xcode#5]
I install using Alcatraz. and I press the allow load the bundle when the xcode restart.

There are the  `Clean Header` in the `Edit` menu, and the shortcut do nothing!

**Comment by insanoid** [comment]
I am on Xcode 7.2 as well, seems to work fine. Wonder if anyone else is having the same problem as you.

**Comment by pffan91** [comment]
It also does not worked for me. After some investigating I find solution. Correct shortcut is Shift + Command + | (this is not I(i), this is a symbol under Enter button). Hope I help someone:)

**Comment by my5201314zwl** [comment]
not work for me too
