### ISSUE TITLE
Keep associated .h file at the top

### ISSUE THREAD

**Issue by ryang1428** [insanoid/CleanHeaders-Xcode#6]
Love this plugin, but one common practice in .m files is to keep that classes .h import at the top of the imports. 

When sorting using this plugin, it will sort it alphabetically along with all of the other headers, so I have to manually put it back at the top. 

Minor, but something that could be improved

**Comment by insanoid** [comment]
I would look into it, meanwhile clang-format already supports sorting with this kind I think (have a look at https://github.com/travisjeffery/ClangFormat-Xcode). I think one of the solutions would be allow the user to opt-in into keeping associated .h file separate.

**Comment by insanoid** [comment]
This is no longer possible with extensions since document information is not available to extensions.
